USE [master]
GO

/****** Object:  Database [Conway]    Script Date: 13/06/2022 11:47:17 ******/
CREATE DATABASE [Conway]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Conway', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Conway.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Conway_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Conway_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Conway].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Conway] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Conway] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Conway] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Conway] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Conway] SET ARITHABORT OFF 
GO

ALTER DATABASE [Conway] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Conway] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Conway] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Conway] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Conway] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Conway] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Conway] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Conway] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Conway] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Conway] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Conway] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Conway] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Conway] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Conway] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Conway] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Conway] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Conway] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Conway] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Conway] SET  MULTI_USER 
GO

ALTER DATABASE [Conway] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Conway] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Conway] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Conway] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Conway] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Conway] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Conway] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Conway] SET  READ_WRITE 
GO


USE [Conway]
GO

/****** Object:  Table [dbo].[BoardCells]    Script Date: 13/06/2022 11:48:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BoardCells](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BoardID] [int] NOT NULL,
	[X] [int] NOT NULL,
	[Y] [int] NOT NULL
) ON [PRIMARY]
GO


USE [Conway]
GO

/****** Object:  Table [dbo].[Boards]    Script Date: 13/06/2022 11:48:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Boards](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Width] [int] NOT NULL,
	[Height] [int] NOT NULL,
	[Description] [varchar](250) NULL
) ON [PRIMARY]
GO


